### PR TITLE
fix: undefined cache key and only using the first feature branch cache

### LINKED ISSUE #13: Fix undefined cache key and only using the first feature branch cache
https://github.com/TAServers/vcpkg-cache/issues/12#issuecomment-2986811151

### PR DESCRIPTION
**Pull request by jahead**
I reversed the if statement and added a filter to project against undefined keys. 

fixes #13

### CODE REVIEW

File: src/helpers.js [hunk 1]
```diff
@@ -68,12 +68,15 @@ export const getExistingCacheEntriesForCurrentBranch = async (token, prefix) =>
...
 
-    actionsCaches.add(...refActionsCaches);
+  if (currentBranchRef === defaultBranchRef) {
+    return actionsCaches;
   }
 
+  const refActionsCaches = await getExistingCacheEntries(token, prefix, currentBranchRef);
+  core.info(`Found ${refActionsCaches.length} caches for current branch ref '${currentBranchRef}'`);
+
+  refActionsCaches.filter((key) => !!key).forEach((cacheKey) => actionsCaches.add(cacheKey));
```
Comment (Derpius) [inline src/helpers.js:79]: I dont think it's possible to get null from the cache list endpoint itself (was just that spreading empty into .add left its param undefined)

May hide issues if the cache list did for some reason though (e.g. due to github instability), but unlikely to matter either way

**Review by Derpius — APPROVED** [review]
LGTM
